version: '3'
services:
  web:
    image: golang:1.14
    ports:
      - "80:8080"
    working_dir: "/go/src/linksmap"
    restart: always
    volumes:
      - .:/go/src/linksmap
    environment: 
      - LINKSMAP_HOSTNAME=${LINKSMAP_HOSTNAME}
    command: "bash -c 'go version && go get ./... && go run ./cmd/'"