version: '3'
services:
  web:
    image: golang:1.13
    ports:
      - "80:8080"
    working_dir: "/go/src/linksmap"
    restart: always
    volumes:
      - .:/go/src/linksmap
    command: "bash -c 'go version && go get ./... && go run ./cmd/linksmap.go'"