name: Deploy

on: 
  push:
    branches: master

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Updating and restarting the service on remote host
      uses: cross-the-world/ssh-pipeline@master
      with:
        host: ${{ secrets.RR_HOST }}
        user: ${{ secrets.RR_USERNAME }}
        key: ${{ secrets.RR_PRIVATE }}
        script: |
          cd dc-apps/go/linksmap/
          docker-compose down
          git reset --hard
          git pull
          go get ./...
          docker-compose up -d
